### ISSUE TITLE
Feature request : Possibility to save/restore current status of the list

### ISSUE THREAD

**Issue by koansoftware** [oleg-shilo/Favorites.vscode#14]
In this great extension I only miss a feature.

I'd like to have the feature of save/restore the current status of the **previously opened files** of the list when you open a list.

(It is a similar request as #7 but quite different)
When you switch from a list to another you get the new list of files available in the FAVORITES box and is fine, but unfortunately if I was working on some of the files and they are opened (and listed in the tabs on the top of the editor window), when I change the list or even close and reopen VScode, I have to re-open them again.

P.S. The extension is currently able to save a list a set of files in an ASCII file (.txt) and I love that because I can edit manually if I want.

Thank you

**Comment by oleg-shilo** [comment]
I cannot reproduce it. 
If I switch between lists and have some of their items/files open restarting VSCode does not seem break the lists or loose opened files.

I cannot reproduce the problem/

**Comment by koansoftware** [comment]
Hi Oleg,
thank you for taking care about my request.

I try to explain it better.
Create two files "a", "b"

Let's start with a clean condition, 
Open VScode and close every file.
running with no opened files (no editors opened).

Clock on the star "Create and loads a new favorites list", and name it "test-ab"
Open a file called "a", and add it to the list "Add active document to favorites"
Open a file called "b", and add it to the list "Add active document to favorites"
If you close and reopen VScode the previously opened files are reopened, and they are members of the list "test-ab".
So far so good.

Now, close all the files again.
VScode running with no opened files (no editors opened).
Close VScode (exit)

Reopen VScode
you won't have any opened file and is as expected

Now how can I open all the files of the list "test-ab" ?
The only possibility seems to be only : clicking on on one of the files member of the list and right click "Open all files from the list"
This is the first point: It is a bit tricky. I expected to be able to opern it right clicking on the Favorite name. However so far so good.

Now the missing feature I pointed out.
If you have two favorite list, you can open all the files fo the first list, then all the files of the second.
The result is a mix (a mess) with files coming from two lists.
I'd like to be able to reopen all the files of the list only every time I switch to a new one.
And closing and reopening VScode shoud remember the favorite list that was opened and consequently reopen all the files of such list only.
 
A similar feature is provided by the extension **oigene.sessions** but that has to main problems:
not listing the files with a tree in the side bar and not having the list of the files in ASCII.

Thank you

**Comment by oleg-shilo** [comment]
OK, I see.

Indeed it makes sense to have this command associated with the lists manager (extension) instead of list item.

Though I do see how sometimes opening files from multiple lists can be useful. Thus will allow an option `favorites.close_previous_list_files` with the default `true`.

Already working on it.

**Comment by oleg-shilo** [comment]
After re-reading your post I realized that what you want is kind of like 'open folder' use case.

### Use-case 1
`close_previous_list_files` will handle "mix (a mess)". Even though it's a bit tricky to implement. But possible.

Tricky because.
- What if the file 'a' was opened with `File->Open`. Should it be closed on "OpenAll for list 'B'?"
- What if the file 'a' was opened with node click. Should it be closed on "OpenAll for list 'B'?"
- How should we consider clicking on `<Open folder>` node?

### Use-case 2

> I'd like to be able to reopen all the files of the list only every time I switch to a new one.

Doable, though cannot be a default option as not everyone would like it. Can be done as an option `favorites.open_all_on_activating_list`. Providing `use-case #1` is solved with adequate UX.

### Use-case 3

> And closing and reopening VScode should remember the favorite list that was opened and consequently reopen all the files of such list only.

It kind of already does. VSCode remembers the last active list and it opens all filse regardless if they are opened via Favorites or by any other way.

**Comment by oleg-shilo** [comment]
I just published release v1.3.6 that have context menu problem sorted out so it will already make your life easier:

All list specific context-menu items moved to the title bar custom menu group `...`

![image](https://user-images.githubusercontent.com/16729806/82788584-0e516400-9eac-11ea-82b1-e0f5369033af.png)
