### ISSUE TITLE
Allow named lists of favorites

### ISSUE THREAD

**Issue by pehrlich** [oleg-shilo/Favorites.vscode#3]
Currently, all favorites show up in one generic "favorites" list.  It would be great if there could be virtual subfolders within this, for keeping track of different work-areas.

**Comment by oleg-shilo** [comment]
I like the idea.
Will do in the next release

**Comment by oleg-shilo** [comment]
Done. Please grab the latest v1.2 release:
![](https://raw.githubusercontent.com/oleg-shilo/Favorites.vscode/master/resources/images/codemap.lists.gif)

**Comment by drahkrub** [comment]
Since this issue is still open:

1. It would be nice, if this plugin would remember the state (or visual appearance) of its "FAVORITES" tab after a (favorite-) folder is clicked (which result is similiar (or identical?) to switching the workspace).
2. Moreover it would be nice if folders would have some "active sign" like the checkmark in front of a selected group name.

**Comment by oleg-shilo** [comment]
Item#1 - yes, it's a good feature to have. Will do it for the next release.
Item#2 - it is already implemented:
![image](https://user-images.githubusercontent.com/16729806/45749881-6c966000-bc50-11e8-9a8c-b5b441102691.png)

**Comment by oleg-shilo** [comment]
OK. I see. 
yes `"Python scripts" is a "favorites list"`. There may be some technical challenges as treeview in VSCode still has some fundamental gaps. But.. I will give it a try.

**Comment by oleg-shilo** [comment]
Done. Will publish shortly.
Though unfortunately `vscode.TreeItem` has no Collapse/Expand event that can be used to detect tree changes and store them for use on the next startup. Thus it is still problematic. :(

**Comment by oleg-shilo** [comment]
Done, published.
