### ISSUE TITLE
Non-path text not work

### ISSUE THREAD

**Issue by wellbloud-cz** [oleg-shilo/Favorites.vscode#42]
Hello,
I have a problem with non-path items. When I try to set it, item is showing as "path item":

![Image 002](https://user-images.githubusercontent.com/57621708/168447617-8e0b8264-c260-4a14-bc54-873404b54c68.png)

I am using this settings:
`favorites.showFolderFiles": true,
 "favorites.singleListMode": true,`

Is there some solution for this?
Thanks.
Kamil

**Comment by oleg-shilo** [comment]
Looking at it

**Comment by oleg-shilo** [comment]
Fixed. Install v1.5.16 
The problem was caused by the need to display the file icon even if the file's existence cannot be checked (e.g. WSL).

Thus a new convention has to be used for separators: `|<separator>`. What is in fact consistent with `<file path>|<file aliase>` where the file path is empty and the file alias is ... your separator.

**Comment by wellbloud-cz** [comment]
It works fine. Thanks.
